import { chromium } from "playwright-core";
import http from "node:http"; import fs from "node:fs"; import path from "node:path";
import { launch, serve, OUT as dir } from "../lib.mjs";
const srv = serve(8773);
const b = await launch();
const pg = await b.newPage({ viewport: { width: 1400, height: 1300 }, deviceScaleFactor: 2 });
const errs = []; pg.on("pageerror", e => errs.push(e.message));
await pg.goto("http://localhost:8773/ovl.html"); await pg.waitForFunction(() => window.__ready); await pg.waitForTimeout(200);
let ok = 0, fail = 0; const t = (n, c) => { c ? ok++ : fail++; console.log(c ? "PASS" : "FAIL", n); };
const z = await pg.locator(".lego-sec-controls").first().boundingBox();
await pg.mouse.dblclick(z.x + z.width - 20, z.y + z.height - 12);
await pg.waitForSelector(".lego-comfy-dialog");
await pg.fill(".lego-comfy-search-input", "strength_clip"); await pg.waitForTimeout(100);
await pg.click(".lego-comfy-node-row >> nth=0"); await pg.waitForTimeout(100);
await pg.click('.lego-comfy-details .lego-whole-node-btn:has-text("row")'); await pg.waitForTimeout(250);
const g = await pg.evaluate(() => JSON.parse(JSON.stringify(__host.properties.ui_layout.tabs[0].sections[0].controls[0])));
t("group header = node title: " + g.header, g.header === "Load LoRA");
t("label inherits the renamed widget label: " + g.items[2].text, g.items[2].text === "LoRa Turbo Strength");
t("header rendered", (await pg.textContent(`.lego-row[data-name="${g.name}"] .lego-seg-header`)) === "Load LoRA");
// seleciona o último stepper (canto direito, como no print) e passa o mouse nele
const last = g.items[g.items.length - 1].name;
await pg.click(`.lego-segment-item[data-name="${last}"]`, { position: { x: 4, y: 4 } }); await pg.waitForTimeout(150);
const it = await pg.locator(`.lego-segment-item[data-name="${last}"]`).boundingBox();
await pg.mouse.move(it.x + it.width / 2, it.y + it.height / 2); await pg.waitForTimeout(250);
const boxes = await pg.evaluate((name) => {
  const row = document.querySelector(".lego-row.is-segment");
  const bar = row.querySelector(":scope > .lego-floating-actions");
  const ia = document.querySelector(`.lego-segment-item[data-name="${name}"] .lego-item-actions`);
  const r = (e) => { const b = e.getBoundingClientRect(); return { l: b.left, t: b.top, r: b.right, b: b.bottom, vis: getComputedStyle(e).opacity !== "0" && getComputedStyle(e).display !== "none" }; };
  const btns = (e) => [...e.querySelectorAll("button")].map(r);
  return { row: r(row), bar: r(bar), barBtns: btns(bar), itemBtns: btns(ia), itemVis: r(ia).vis };
}, last);
const hit = boxes.barBtns.some(a => boxes.itemBtns.some(c => a.l < c.r && a.r > c.l && a.t < c.b && a.b > c.t));
t(`group bar and item buttons both visible (${boxes.bar.vis}/${boxes.itemVis}) and don't overlap`, boxes.bar.vis && boxes.itemVis && !hit);
t("group bar sits above the group border", boxes.barBtns.every(bb => bb.b <= boxes.row.t + 1));
// barra do grupo alcançável: mover até ela mantém visível e o clique funciona
const add = await pg.locator(".lego-row.is-segment > .lego-floating-actions .btn-add").boundingBox();
await pg.mouse.move(boxes.row.l + 20, boxes.row.t + 6); await pg.mouse.move(add.x + add.width / 2, add.y + add.height / 2, { steps: 8 }); await pg.waitForTimeout(150);
console.log("DEBUG", JSON.stringify(await pg.evaluate(([x,y]) => { const e = document.elementFromPoint(x,y); const bar = document.querySelector(".lego-row.is-segment > .lego-floating-actions"); return { at: e?.className?.baseVal ?? e?.className, tag: e?.tagName, parent: e?.closest("button")?.className, barOpacity: getComputedStyle(bar).opacity, barPE: getComputedStyle(bar).pointerEvents }; }, [add.x + add.width/2, add.y + add.height/2])));
await pg.mouse.click(add.x + add.width / 2, add.y + add.height / 2); await pg.waitForTimeout(150);
t("group + Add reachable from the group (opens dialog)", !!(await pg.$(".lego-comfy-dialog")));
await pg.keyboard.press("Escape"); await pg.waitForTimeout(100);
t("Esc closes the search dialog even with a component selected", !(await pg.$(".lego-comfy-dialog")));
await pg.click(`.lego-segment-item[data-name="${last}"]`, { position: { x: 4, y: 4 } }); await pg.waitForTimeout(100);
await pg.mouse.move(it.x + it.width / 2, it.y + it.height / 2); await pg.waitForTimeout(250);
const rr = await pg.locator(".lego-row.is-segment").boundingBox();
await pg.screenshot({ path: path.join(dir, "overlap_fixed.png"), clip: { x: rr.x + rr.width - 420, y: rr.y - 50, width: 440, height: rr.height + 70 } });
t("no page errors " + JSON.stringify(errs), !errs.length);
console.log(`\n${ok} passed, ${fail} failed`);
await b.close(); srv.close();
process.exit(fail ? 1 : 0);
