import { chromium } from "playwright-core";
import http from "node:http"; import fs from "node:fs"; import path from "node:path";
import { launch, serve, OUT as dir } from "../lib.mjs";
const srv = serve(8771);
const b = await launch();
const pg = await b.newPage({ viewport: { width: 1400, height: 1300 } });
const errs = []; pg.on("pageerror", e => errs.push(e.message));
await pg.goto("http://localhost:8771/whole.html"); await pg.waitForFunction(() => window.__ready); await pg.waitForTimeout(200);
let ok = 0, fail = 0; const t = (n, c) => { c ? ok++ : fail++; console.log(c ? "PASS" : "FAIL", n); };
const addWhole = async (which, filter) => {
  const z = await pg.locator(".lego-sec-controls").first().boundingBox();
  await pg.mouse.dblclick(z.x + z.width - 20, z.y + z.height - 12);
  await pg.waitForSelector(".lego-comfy-dialog");
  await pg.fill(".lego-comfy-search-input", filter); await pg.waitForTimeout(100);
  await pg.click(".lego-comfy-node-row >> nth=0"); await pg.waitForTimeout(100);
  await pg.click(`.lego-comfy-details .lego-whole-node-btn:has-text("${which}")`); await pg.waitForTimeout(200);
};
await addWhole("row", "strength_model");
const L = () => pg.evaluate(() => JSON.parse(JSON.stringify(__host.properties.ui_layout.tabs[0].sections[0].controls)));
let c = await L();
const g = c[0];
t("row: horizontal group created", g && g.kind === "segment" && g.label === "Load LoRA");
t("row items = Label,Dropdown,Label,Stepper,Label,Stepper: " + g.items.map(i => i.kind).join(), g.items.map(i => i.kind).join() === "label,combo,label,number,label,number");
t("binds point at node 12: " + g.items.filter(i=>i.bind).map(i=>i.bind).join(), g.items.filter(i=>i.bind).map(i=>i.bind).join() === "12/lora_name,12/strength_model,12/strength_clip");
t("unique names", new Set([g.name, ...g.items.map(i => i.name)]).size === 7);
t("dialog closed", !(await pg.$(".lego-comfy-dialog")));
await addWhole("column", "clip_name");
c = await L();
const v = c[1];
t("column: vertical group with 3 labels + 3 dropdowns", v && v.kind === "vsegment" && v.items.map(i => i.kind).join() === "label,combo,label,combo,label,combo");
t("no overlap between the two groups", !(v.y < g.y + g.h && v.y + v.h > g.y && v.x < g.x + g.w && v.x + v.w > g.x));
// o widget criado controla o nó de verdade
await pg.evaluate(() => { __st.edit = false; __st.refresh(); }); await pg.waitForTimeout(150);
await pg.click(`.lego-segment-item[data-name="${g.items[3].name}"] .lego-step-btn:has-text("+")`); await pg.waitForTimeout(100);
t("stepper drives LoraLoader.strength_model: " + await pg.evaluate(() => __lora.widgets[1].value), Math.abs((await pg.evaluate(() => __lora.widgets[1].value)) - 1.01) < 1e-9);
await pg.screenshot({ path: path.join(dir, "whole_view.png"), clip: { x: 0, y: 0, width: 800, height: 520 } });
await pg.keyboard.press("Escape");
t("no page errors " + JSON.stringify(errs), !errs.length);
console.log(`\n${ok} passed, ${fail} failed`);
await b.close(); srv.close();
process.exit(fail ? 1 : 0);
