import { chromium } from "playwright-core";
import path from "node:path";
import { launch, COMFY_URL, OUT as dir } from "../lib.mjs";
const b = await launch();
const pg = await b.newPage({ viewport: { width: 1400, height: 900 } });
const errs = []; pg.on("pageerror", e => errs.push(e.message));
await pg.goto(COMFY_URL);
await pg.waitForFunction(() => !!window.app?.graph && !!window.app?.extensions?.find(e => e.name === "ComfyUI.SuperSubgraph"), null, { timeout: 90000 });
await pg.waitForTimeout(1500); await pg.keyboard.press("Escape");
let ok = 0, fail = 0; const t = (n, c) => { c ? ok++ : fail++; console.log(c ? "PASS" : "FAIL", n); };
const E = (f, a) => pg.evaluate(f, a);
const ids = await E(async () => {
  const app = window.app; app.graph.clear(); const LG = window.LiteGraph;
  const mk = (type, x, y) => { const n = LG.createNode(type); n.pos = [x, y]; app.graph.add(n); return n; };
  const I = mk("LoadImage", 0, 0), A = mk("LoadAudio", 400, 0), V = mk("LoadVideo", 800, 0), M = mk("LoadImageMask", 0, 450);
  app.canvas.deselectAll?.(); for (const n of [I, A, V, M]) app.canvas.select(n);
  app.extensions.find(e => e.name === "ComfyUI.SuperSubgraph").__flatCanvas().find(i => i && /Convert/.test(i.content)).callback();
  const sn = app.graph.nodes.find(n => n.type === "SuperSubgraph");
  app.canvas.ds.offset = [80 - sn.pos[0], 80 - sn.pos[1]]; app.canvas.ds.scale = 1; app.canvas.setDirty(true, true);
  return { sn: sn.id, I: I.id, A: A.id, V: V.id, M: M.id };
});
await pg.waitForTimeout(500);
await pg.locator(".lego-head-tools .lego-iconbtn:not(.lego-ss-enter)").last().click(); await pg.waitForTimeout(300);
await pg.locator(".lego-zone-dropzone").dblclick(); await pg.waitForTimeout(300);
await pg.locator(".lego-comfy-target-picker-btn").click(); await pg.waitForTimeout(700);
const titlePos = (id) => E((id) => { const c = window.app.canvas; const n = c.graph.getNodeById(id); const r = c.canvas.getBoundingClientRect(); const T = window.LiteGraph.NODE_TITLE_HEIGHT || 30; return [r.left + (n.pos[0] + 30 + c.ds.offset[0]) * c.ds.scale, r.top + (n.pos[1] - T / 2 + c.ds.offset[1]) * c.ds.scale]; }, id);
for (const id of [ids.I, ids.A, ids.V, ids.M]) { const [x, y] = await titlePos(id); await pg.mouse.click(x, y); await pg.waitForTimeout(120); }
t("4 whole nodes picked", /Promote \(4\)/.test(await pg.locator(".lego-picker-promote-btn").innerText()));
await pg.locator(".lego-picker-promote-btn").click(); await pg.waitForTimeout(600);
const res = await E((sid) => window.app.graph.getNodeById(sid).properties.ui_layout.tabs[0].sections[0].controls.map(c => ({ kind: c.kind, bind: c.bind, items: (c.items || []).map(i => `${i.kind}:${i.bind || i.text}`) })), ids.sn);
console.log(JSON.stringify(res));
const byBind = (b) => res.find(c => c.bind === b);
t("Load Image -> just an Image Upload component", byBind(`${ids.I}/image`)?.kind === "media");
t("Load Audio -> just an Audio Upload component", byBind(`${ids.A}/audio`)?.kind === "audio");
t("Load Video -> just a Video Upload component", byBind(`${ids.V}/file`)?.kind === "video");
const mask = res.find(c => c.kind === "segment" && c.items.some(i => i.endsWith(`${ids.M}/channel`)));
t("Load Image (as Mask) -> group with media + channel, no upload button", mask && mask.items.join() === `media:${ids.M}/image,label:Channel,combo:${ids.M}/channel`);
t("no upload/$$ helpers anywhere", !JSON.stringify(res).includes("/upload") && !JSON.stringify(res).includes("$$"));
await pg.waitForTimeout(400);
await pg.screenshot({ path: path.join(dir, "media_promote.png") });
t("no page errors " + JSON.stringify(errs), !errs.length);
console.log(`\n${ok} passed, ${fail} failed`);
await b.close();
process.exit(fail ? 1 : 0);
